# Python Libraries

In Python there are different libraries which makes programming in Python fast. Libraries contain a number of code inside it, these codes are useful for doing specific tasks. In order to use these Libraries one has to install the packages from their link and then import them before using it.

# Numpy

Numpy is mathematical package which helps in matrix addition, subtraction, multiplication, linear algebra, Fourier transform and many more operations. It is convenient to use Numpy as the processing speed of this library is fast, and it makes the programming easy.   

# Install Numpy using Python 3

Before using the Numpy library, it is important to install it into the system. To install the Numpy library, open Python and enter the following command on it: 
1. python -m pip install numpy


# Import Numpy 

After installing the library, import it in order to use it in our code. To import the Numpy Library enter command "import numpy" this will import the library and it can be used. As Numpy will be used several times to save time we use "np" as a abbreviation for Numpy.
Below is the way for importing the library.

In [1]:
import numpy as np

# Arrays

Numpy contains data of a same kind and are stored as an arrays. It can store multi-dimensional data, the dimensions are given by x, y, Z,.. axis. 
Below is an example of how to create an array.

In [56]:
aa=np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [57]:
aa

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

# Data type

Numpy provide it's own data size type. It has numpy.int32, numpy.int16, and numpy.float64 etc data types.

Below is the way to see the data type:

In [8]:
aa.dtype

dtype('int32')

# Specify data type

It is possible to specify the type of the data. It can be as follows: 

In [9]:
aa=np.array([1,2,3,4,5],dtype=np.float64)

In [10]:
aa

array([1., 2., 3., 4., 5.])

In [12]:
aa.dtype

dtype('float64')

#  Array's Dimention, Shape, Size.

It is possible to check the size, shape, and dimention of the array. To check it the following code is given: 

In [13]:
aa.ndim, aa.shape, aa.size

(1, (5,), 5)

In [14]:
aa=np.array([[1,2,3],[4,7,8]], dtype=np.float64)

In [15]:
aa

array([[1., 2., 3.],
       [4., 7., 8.]])

In [18]:
b=np.zeros([2,2])
b

array([[0., 0.],
       [0., 0.]])

In [16]:
aa.ndim, aa.shape, aa.size

(2, (2, 3), 6)

In [19]:
b.dtype

dtype('float64')

# Creating a zero element array

In [20]:
b=np.zeros([2,2],'d')
b

array([[0., 0.],
       [0., 0.]])

In [22]:
b.dtype

dtype('float64')

# Creating arrays with specific number of values in it.

In [60]:
zz=np.arange(5)
zz

array([0, 1, 2, 3, 4])

In [26]:
np.linspace(0,20,10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [28]:
np.empty((4,4),'d')

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        6.23058707e-307],
       [2.22522597e-306, 1.33511969e-306, 1.37962320e-306,
        9.34604358e-307],
       [9.79101082e-307, 1.78020576e-306, 1.69119873e-306,
        2.22522868e-306],
       [1.24611809e-306, 8.06632139e-308, 1.60221208e-306,
        2.29178686e-312]])

# Create a random array with dimensions

In [65]:
a=np.random.standard_normal((3,2))


In [63]:
b=np.random.standard_normal((3,2))


In [35]:
a

array([[-0.88510933,  1.1710384 ],
       [ 0.50962518, -1.33696484],
       [-0.04597801,  0.23538709]])

In [36]:
b

array([[-0.51601263, -0.00902372],
       [-1.20230033, -0.64357166],
       [ 1.40497535,  0.02452747]])

# Creating an array and using trignometric operations on it.

In [37]:
x=np.linspace(0,10,40)

In [38]:
x

array([ 0.        ,  0.25641026,  0.51282051,  0.76923077,  1.02564103,
        1.28205128,  1.53846154,  1.79487179,  2.05128205,  2.30769231,
        2.56410256,  2.82051282,  3.07692308,  3.33333333,  3.58974359,
        3.84615385,  4.1025641 ,  4.35897436,  4.61538462,  4.87179487,
        5.12820513,  5.38461538,  5.64102564,  5.8974359 ,  6.15384615,
        6.41025641,  6.66666667,  6.92307692,  7.17948718,  7.43589744,
        7.69230769,  7.94871795,  8.20512821,  8.46153846,  8.71794872,
        8.97435897,  9.23076923,  9.48717949,  9.74358974, 10.        ])

In [39]:
sinx=np.sin(x)

In [40]:
sinx

array([ 0.        ,  0.25360981,  0.49063689,  0.69558279,  0.85504677,
        0.95860198,  0.99947728,  0.97499996,  0.88677052,  0.740558  ,
        0.54592277,  0.31559139,  0.06462451, -0.19056796, -0.43329981,
       -0.64769957, -0.81974833, -0.93819637, -0.99529876, -0.98732176,
       -0.91478695, -0.78243716, -0.59892631, -0.37625358, -0.12897884,
        0.12672941,  0.37415123,  0.5971085 ,  0.78102277,  0.91386845,
        0.98695921,  0.99551587,  0.93897894,  0.82104518,  0.64942592,
        0.43534277,  0.19279396, -0.06236104, -0.31343844, -0.54402111])

In [66]:
cosx=np.cos(x)

In [67]:
cosx

array([ 1.        ,  0.9673066 ,  0.87136413,  0.71844595,  0.51855089,
        0.28474945,  0.03232915, -0.22220504, -0.46220996, -0.67199245,
       -0.8378355 , -0.94889519, -0.99790965, -0.981674  , -0.90124984,
       -0.76189584, -0.57272391, -0.3461034 , -0.0968523 ,  0.15873166,
        0.40393667,  0.62272955,  0.80080415,  0.92651672,  0.99164735,
        0.99193733,  0.9273677 ,  0.80216048,  0.62450255,  0.40601041,
        0.16097054, -0.09459467, -0.34397464, -0.57086321, -0.76042487,
       -0.90026478, -0.98123926, -0.99805366, -0.94960852, -0.83907153])

# Creating array and using multiplication on it.

In [68]:
A= np.arange(4).reshape(2,2)
A

array([[0, 1],
       [2, 3]])

In [69]:
B=np.arange(4).reshape(2,2)
B

array([[0, 1],
       [2, 3]])

In [70]:
#elementwise product
A*B

array([[0, 1],
       [4, 9]])

In [71]:
 # matrix product
A@B    

array([[ 2,  3],
       [ 6, 11]])

In [82]:
#Total sum of matrix
A.sum()

6

# Indexing, Slicing and Iterating

As we have seen in python list, set, etc indexing, Slicing and Iterating is also possible in Numpy.

# Indexing

In [83]:
#For a single dimensional array.
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [84]:
b=a[2]
b

2

In [86]:
b=a[5:9]
b

array([5, 6, 7, 8])

In [88]:
# For multi-dimensional array
a=np.array([[1,2,3],[5,8,9],[8,7,4]])
a

array([[1, 2, 3],
       [5, 8, 9],
       [8, 7, 4]])

In [91]:
a[1,1]

8

In [93]:
a[0,2]

3

# slicing

In [95]:
#Similar to the list slicing.
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [96]:
a[1:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [99]:
a=np.arange(6).reshape(3,2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [110]:
#2 dimensional slicing
a[(0,1),1]

array([1, 3])

In [125]:
a[2,0:2]

array([4, 5])

# Boolean slicing

It is done by set some equation to the variable.

In [127]:

a=np.arange(10,20)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [128]:
a[a>15]

array([16, 17, 18, 19])

# vertical and horizontal stacking.

In [133]:
a=np.array([1,2,3])
b=np.array([5,9,8])
a


array([1, 2, 3])

In [134]:
b

array([5, 9, 8])

In [138]:
aa=np.vstack((a,b))
aa

array([[1, 2, 3],
       [5, 9, 8]])

In [139]:
bb=np.hstack((a,b))
bb

array([1, 2, 3, 5, 9, 8])